#cloud-config
keyboard:
  layout: jp
  model: jp106
locale: ja_JP.UTF-8
package_reboot_if_required: true
package_update: true
package_upgrade: false
packages:
  - language-pack-ja
  - nodejs
  - taskwarrior
runcmd:
  - systemctl daemon-reload
  - systemctl enable automata.service
  - apt-get -y autoremove
  - apt-get clean
timezone: Asia/Tokyo
write_files:
  - path: /etc/apt/apt.conf.d/99no-recommends
    content: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
  - path: /etc/apt/preferences.d/999-hold-kernel.pref
    content: |
      Package: linux-generic*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-headers*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-image*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-modules*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-modules-extra*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-tools*
      Pin: release a=*
      Pin-Priority: -1

      Package: linux-virtual*
      Pin: release a=*
      Pin-Priority: -1
  - path: /etc/skel/.sudo_as_admin_successful
    content: ''
  - path: /etc/skel/.taskrc
    content: |
      data.location=~/.task
      confirmation=0
      include dark-256.theme
  - path: /etc/systemd/system/automata.service
    content: |
      [Unit]
      Description=Automata
      After=cloud-init.target network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=ubuntu
      Group=ubuntu
      WorkingDirectory=/home/ubuntu
      ExecStart=/opt/automata/package/dist/bin.mjs
      Restart=always
      RestartSec=60
      Environment=HOME=/home/ubuntu
      Environment=PATH=/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

      [Install]
      WantedBy=multi-user.target
  - path: /opt/automata/deploy
    permissions: '0755'
    content: |
      #!/bin/sh
      set -eu
      sleep 1
      tar xzvf /tmp/automata.tgz -C /opt/automata
      rm -f /tmp/automata.tgz
      mkdir -p /opt/automata/var
      chmod 777 /opt/automata/var
      systemctl restart --no-block automata.service
