allowCompoundWords: true
dictionaries:
  - cpp-compound-words
  - docker
  - en_US
  - en-gb
  - git
  - markdown
  - misc
  - python
  - softwareTerms
  - terraform
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .terraform.lock.hcl
  - .vscode/extensions.json
  - cspell.config.yml
language: en,ja
useGitignore: true
version: '0.2'
words:
  - buildx
  - imgbotconfig
  - kito
  - kuron
  - kuroné
  - larstobi
  - libasound
  - libatk
  - libatspi
  - libnspr
  - libgbm
  - libpango
  - libx
  - libxcomposite
  - libxdamage
  - libxext
  - libxfixes
  - libxkbcommon
  - libxrandr
  - nocaps
  - nopw
  - rfbport
  - setxkbmap
  - skel
  - xorg
  - xrdp
  - xsessionrc
