cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - cpp-compound-words
  - terraform
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - giget
  - larstobi
