#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

set -eu

rm -f automata.tar
if command -v terraform >/dev/null 2>&1
then
  terraform destroy -auto-approve || true
  multipass delete -p automata || true
fi
